# Generated by Django 4.2 on 2023-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creams',
            name='brief_info_about_product',
            field=models.CharField(blank=True, max_length=25, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='creams',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='creams',
            name='title_of_product',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='creams',
            name='type_of_derm',
            field=models.CharField(max_length=50, verbose_name='Тип кожи'),
        ),
    ]
