# Generated by Django 4.2 on 2023-04-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_creams_filters_perfumes_filters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creams",
            name="filters",
        ),
        migrations.RemoveField(
            model_name="perfumes",
            name="filters",
        ),
        migrations.CreateModel(
            name="Categoty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=15, verbose_name="Категория")),
                (
                    "filters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.modelfilters",
                    ),
                ),
            ],
        ),
    ]
