# Generated by Django 4.2 on 2023-04-18 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_rename_brief_info_about_product_creams_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="creams",
            name="isHit",
            field=models.BooleanField(default=False, verbose_name="Хит"),
        ),
        migrations.AddField(
            model_name="creams",
            name="sale",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(0)],
                verbose_name="Скидка",
            ),
        ),
    ]
