# Generated by Django 4.2 on 2023-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_remove_creams_filters_remove_perfumes_filters_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoty",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="modelfilters",
            options={"verbose_name": "Фильтр", "verbose_name_plural": "Фильтры"},
        ),
        migrations.RemoveField(
            model_name="categoty",
            name="filters",
        ),
        migrations.AddField(
            model_name="categoty",
            name="filters",
            field=models.ManyToManyField(to="catalog.modelfilters"),
        ),
    ]
