# Generated by Django 4.2 on 2023-04-24 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_categoty_options_alter_modelfilters_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categoty",
            new_name="Category",
        ),
    ]
