# Generated by Django 4.2 on 2023-04-19 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_creams_ishit_creams_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creams",
            name="isHit",
        ),
        migrations.AddField(
            model_name="creams",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AlterField(
            model_name="creams",
            name="sale",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Скидка, %",
            ),
        ),
    ]
